apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
source:
  repoURL: 'https://github.com/lucaz1992/Argo_CD'
  path: backend
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
