project: default
source:
  repoURL: 'https://github.com/lucaz1992/Argo_CD'
  path: frontend
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy: {}
